######################################################################
# Automatically generated by qmake (2.01a) Mo Okt 30 15:20:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += "/Users/markuseberherr/Eigene Programme/Qt/Additionsprogramm/." .

# Input
FORMS += Additionsprogramm.ui
HEADERS = Additionsprogramm.h ui_Additionsprogramm.h
SOURCES = main.cpp Additionsprogramm.cpp